# 验证就绪探针的持续时间
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: wangyanglinux/tools:busybox
      command: ["/bin/sh", "-c", "touch /tmp/live; sleep 60; rm -rf /tmp/live; sleep 3600"]
      imagePullPolicy: IfNotPresent
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/live
        initialDelaySeconds: 5
        periodSeconds: 5
