apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  selector:
    app: myapp
    release: demo
    svc: nodeport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
