apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nginx-1
  labels:
    kubernetes.io/service-name: nginx
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.244.10.87"
    conditions:
      ready: true

