apiVersion: v1
kind: Secret
metadata:
  name: se-op
type: Opaque
data:
  username: "bHl5ZHNoZWVw"
  password: "MTIzNDU2"

---
apiVersion: v1
kind: Pod
metadata:
  name: se-op-pod
  labels:
    role: se-op-pod
spec:
  containers:
    - name: se-op-pod
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name:  username
          valueFrom:
              secretKeyRef:
                  name: se-op
                  key: username
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: se-op-pod-subpath
  labels:
    role: se-op-pod-subpath
spec:
  volumes:
    - name: se-op-subpath
      secret:
          secretName: se-op
          items:
              - key: username
                path: username
  containers:
    - name: se-op-pod-subpath
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: se-op-subpath
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: se-op-pod-volume
  labels:
    role: se-op-pod-volume
spec:
  volumes:
    - name: se-op-volume
      secret:
          secretName: se-op
  containers:
    - name: se-op-pod-volume
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: se-op-volume
  restartPolicy: Always
