apiVersion: v1
kind: Pod
metadata:
  name: se-op-true-subpath-pod
  labels:
    role: se-op-true-subpath-pod
spec:
  volumes:
    - name: se-op-true-subpath-pod-volume
      secret:
        secretName: se-op
        items:
          - key: username
            path: data/username
            mode: 0400
          - key: password
            path: password
            mode: 0400
  containers:
    - name: se-op-true-subpath-pod
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: se-op-true-subpath-pod-volume
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: subpath-se
  labels:
    role: subpath-se
spec:
  volumes:
    - name: subpath-se-volume
      secret:
        secretName: se-op
  containers:
    - name: subpath-se
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data/username
          name: subpath-se-volume
          subPath: username
  restartPolicy: Always
