apiVersion: v1
kind: Pod
metadata:
  name: dw-api-pod
  labels:
    role: dw-api-pod
spec:
  volumes:
    - name: dw-api-pod-volume
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
  containers:
    - name: dw-api-pod
      image: wangyanglinux/myapp:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: "/etc/pod-labels"
          name: dw-api-pod-volume
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
  restartPolicy: Always
