apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 10
  parallelism: 5
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: myjob-container
          image: wangyanglinux/tools:randexitv1
      restartPolicy: Never
